version: '3.4'

services:
  com.tweetapp.api:
    image: ${DOCKER_REGISTRY-}comtweetappapi
    build:
      context: .
      dockerfile: com.tweetapp.api/Dockerfile
     
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq    
    ports:
      - 5672:5672
      - 15672:15672
    expose:
     - 5672
     - 15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  